spring:
  application:
    name: load-balancer-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# Logging Configuration
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

